// <auto-generated />
namespace EverythingFuneral.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ModelsChnage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelsChnage));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251445139_ModelsChnage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
